# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c88a35b40f75b7705386c6ecc1bfb56ac133a41453600842d934e24a89e8272e3c624f5876b0d640b27a4fa0059f53a5bcd5feaebe1659dfb83dc8c2b0728d97

test:
  secret_key_base: 11e5fe480b651d4c653a53f18c1654341c26616eb86cd1c6978f24f921928ebcf3a07a8390fda0e49902b286abde1a744dfb11de6db333d41fff59058217911f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
